new ux design
kadaster-labs/solid-quest pull request #58
Opened 2023-03-02 14:11 UTC by marcvanandel

The new UX design works ... with a [BottomNavigation](https://mui.com/material-ui/react-bottom-navigation/#fixed-positioning) ... which might not be as nice as the footer I had in the [other branch](https://github.com/kadaster-labs/solid-quest/tree/feat/ux-background) ...

It looks OK now:

![image](https://user-images.githubusercontent.com/2315396/222452273-2e97e1e3-5a31-42f7-b552-e65a6a68365b.png)

2023-03-06 18:13 UTC, kad-busses requested changes
Goed werk, Marc! Alleen bedenkingen bij de BottomNavigation, zie comment. Verder alleen kleine dingen 😊

2023-03-07 06:17 UTC, marcvanandel commented on koopovereenkomst-v3-simple/src/theme.ts
> +  let t = deepmerge(commonTokens, getDesignTokens(mode));
Met de spread operator merge je alleen objecten van het eerste niveau. Nu raakte ik dieper gelegen objecten kwijt en moest ik een alternatieve manier zoeken. Daarom een `deepmerge` ...

2023-03-07 06:18 UTC, marcvanandel commented on koopovereenkomst-v3-simple/src/Layout.tsx
> +                        <BottomNavigation
Agree ... 'k Zal nog een poging wagen 😉

2023-03-07 06:19 UTC, marcvanandel commented on koopovereenkomst-v3-simple/src/Layout.tsx
> +                    <Link href="https://www.kadaster.nl" target="blank">
OK. Goed punt! (en hangt samen met de BottomNavigation ... die even niet anders lukte 😇 )

2023-03-07 06:20 UTC, marcvanandel commented on koopovereenkomst-v3-simple/pages/_app.tsx
> +  const prefersDarkMode = useMediaQuery('(prefers-color-scheme: dark)');
😇

2023-03-07 06:21 UTC, marcvanandel commented on koopovereenkomst-v3-simple/pages/_app.tsx
> +  const prefersDarkMode = useMediaQuery('(prefers-color-scheme: dark)');
I know ... 😃 Maar ik vind de dark design misschien nog wel mooier dan de light design 😁 In ieder geval vind ik de witte letters in het light design niet zo heel duidelijk. Misschien zouden we dat dan nog 's moeten bespreken?

2023-03-08 06:41 UTC, kad-busses commented on koopovereenkomst-v3-simple/src/theme.ts
> +  let t = deepmerge(commonTokens, getDesignTokens(mode));
Verrek, je hebt helemaal gelijk! Dan heb ik niks gezegd 🙊 Had een visuele test gedaan en kreeg wel gewoon een light en dark theme, had daardoor de (te) snelle aanname gedaan dat het gewoon werkte. Zag dat er ook genoeg aparte libraries zijn die dit toevoegen, maar misschien wel zo clean om het gewoon zelf te implementeren, is immers 1 functie 😁 Vind het wel crazy dat dit niet in de standard library zit trouwens 😇

2023-03-15 10:28 UTC, marcvanandel commented on koopovereenkomst-v3-simple/src/Layout.tsx
> +                        <BottomNavigation
Done 😎

2023-03-15 10:28 UTC, marcvanandel commented on koopovereenkomst-v3-simple/src/Layout.tsx
> +                    <Link href="https://www.kadaster.nl" target="blank">
✅

2023-03-15 16:38 UTC, kad-busses approved these changes
🚀

2023-03-16 07:43 UTC, merged